## OJO ALVARO!!! CORRE EL CODIGO ENTERO DE CADA SECCIÓN CADA VEZ QUE QUIERAS MODIFICAR ALGO !!!

Goal: Handle missing values, non-numeric values, data leakage, and more (using the Melbourne dataset).

https://www.kaggle.com/learn/intermediate-machine-learning

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the data
data = pd.read_csv("/Users/alvaromartinezmartinez/Desktop/Python/MLJupyter/melb_data.csv") 

# Select target
y = data.Price

# To keep things simple, we'll use only numerical predictors
melb_predictors = data.drop(['Price'], axis=1)
X = melb_predictors.select_dtypes(exclude=['object'])

# Divide data into training and validation subsets
X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,random_state=0)

In [2]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Function for comparing different approaches
def score_dataset(X_train, X_valid, y_train, y_valid):
    model = RandomForestRegressor(n_estimators=10, random_state=0)
    model.fit(X_train, y_train)
    preds = model.predict(X_valid)
    return mean_absolute_error(y_valid, preds)

## Missing values

There are three different approaches to handle missing values (https://www.kaggle.com/code/alexisbcook/missing-values).

1) Drop columns with missing values: Simplest option but with the worst results.

In [3]:
# Get names of columns with missing values
cols_with_missing = [col for col in X_train.columns if X_train[col].isnull().any()]

# Drop columns in training and validation data
reduced_X_train = X_train.drop(cols_with_missing, axis=1)
reduced_X_valid = X_valid.drop(cols_with_missing, axis=1)

print("MAE from Approach 1 (Drop columns with missing values):")
print(score_dataset(reduced_X_train, reduced_X_valid, y_train, y_valid))

MAE from Approach 1 (Drop columns with missing values):
183550.22137772635

2) Imputation: fills in the missing values with some number, for instance, we can fill in the mean value along each column.

In [4]:
from sklearn.impute import SimpleImputer

# Imputation
my_imputer = SimpleImputer()
imputed_X_train = pd.DataFrame(my_imputer.fit_transform(X_train))
imputed_X_valid = pd.DataFrame(my_imputer.transform(X_valid))

# Imputation removed column names; put them back
imputed_X_train.columns = X_train.columns
imputed_X_valid.columns = X_valid.columns

print("MAE from Approach 2 (Imputation):")
print(score_dataset(imputed_X_train, imputed_X_valid, y_train, y_valid))

MAE from Approach 2 (Imputation):
178166.46269899711

3) Extension to imputation: standard approach, and it usually works well. However, imputed values may be systematically above or below their actual values (which weren't collected in the dataset). Or rows with missing values may be unique in some other way. In that case, your model would make better predictions by considering which values were originally missing.

In [5]:
# Make copy to avoid changing original data (when imputing)
X_train_plus = X_train.copy()
X_valid_plus = X_valid.copy()

# Make new columns indicating what will be imputed
for col in cols_with_missing:
    X_train_plus[col + '_was_missing'] = X_train_plus[col].isnull()
    X_valid_plus[col + '_was_missing'] = X_valid_plus[col].isnull()

# Imputation
my_imputer = SimpleImputer()
imputed_X_train_plus = pd.DataFrame(my_imputer.fit_transform(X_train_plus))
imputed_X_valid_plus = pd.DataFrame(my_imputer.transform(X_valid_plus))

# Imputation removed column names; put them back
imputed_X_train_plus.columns = X_train_plus.columns
imputed_X_valid_plus.columns = X_valid_plus.columns

print("MAE from Approach 3 (An Extension to Imputation):")
print(score_dataset(imputed_X_train_plus, imputed_X_valid_plus, y_train, y_valid))

MAE from Approach 3 (An Extension to Imputation):
178927.503183954

In [6]:
# Shape of training data (num_rows, num_columns)
print(X_train.shape)

# Number of missing values in each column of training data
missing_val_count_by_column = (X_train.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0])

(10864, 12)
Car               49
BuildingArea    5156
YearBuilt       4307
dtype: int64

## Categorical values

A categorical variable takes only a limited number of values. Consider a survey that asks how often you eat breakfast and provides four options: "Never", "Rarely", "Most days", or "Every day". In this case, the data is categorical, because responses fall into a fixed set of categories.

You will get an error if you try to plug these variables into most machine learning models in Python without preprocessing them first. In this tutorial, we'll compare three approaches that you can use to prepare your categorical data.

In [7]:
# Separate target from predictors
y = data.Price
X = data.drop(['Price'], axis=1)

# Divide data into training and validation subsets
X_train_full, X_valid_full, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,random_state=0)

# Drop columns with missing values (simplest approach)
cols_with_missing = [col for col in X_train_full.columns if X_train_full[col].isnull().any()] 
X_train_full.drop(cols_with_missing, axis=1, inplace=True)
X_valid_full.drop(cols_with_missing, axis=1, inplace=True)

# "Cardinality" means the number of unique values in a column
# Select categorical columns with relatively low cardinality (convenient but arbitrary)
low_cardinality_cols = [cname for cname in X_train_full.columns if X_train_full[cname].nunique() < 10 and X_train_full[cname].dtype == "object"]

# Select numerical columns
numerical_cols = [cname for cname in X_train_full.columns if X_train_full[cname].dtype in ['int64', 'float64']]

# Keep selected columns only
my_cols = low_cardinality_cols + numerical_cols
X_train = X_train_full[my_cols].copy()
X_valid = X_valid_full[my_cols].copy()

In [8]:
X_train.head()

,Type,Method,Regionname,Rooms,Distance,Postcode,Bedroom2,Bathroom,Landsize,Lattitude,Longtitude,Propertycount
12167,u,S,Southern Metropolitan,1,5.0,3182.0,1.0,1.0,0.0,-37.85984,144.9867,13240.0
6524,h,SA,Western Metropolitan,2,8.0,3016.0,2.0,2.0,193.0,-37.85800,144.9005,6380.0
8413,h,S,Western Metropolitan,3,12.6,3020.0,3.0,1.0,555.0,-37.79880,144.8220,3755.0
2919,u,SP,Northern Metropolitan,3,13.0,3046.0,3.0,1.0,265.0,-37.70830,144.9158,8870.0
6043,h,S,Western Metropolitan,3,13.3,3020.0,3.0,1.0,673.0,-37.76230,144.8272,4217.0

In [9]:
# Get list of categorical variables
s = (X_train.dtypes == 'object')
object_cols = list(s[s].index)

print("Categorical variables:")
print(object_cols)

Categorical variables:
['Type', 'Method', 'Regionname']

We also have 3 different approaches to handling this data (https://www.kaggle.com/code/alexisbcook/categorical-variables).

1) Drop Categorical Variables: The easiest approach to dealing with categorical variables is to simply remove them from the dataset. This approach will only work well if the columns did not contain useful information.

In [10]:
drop_X_train = X_train.select_dtypes(exclude=['object'])
drop_X_valid = X_valid.select_dtypes(exclude=['object'])

print("MAE from Approach 1 (Drop categorical variables):")
print(score_dataset(drop_X_train, drop_X_valid, y_train, y_valid))

MAE from Approach 1 (Drop categorical variables):
183550.22137772635

2) Ordinal Encoding: Ordinal encoding assigns each unique value to a different integer. For example, if we have a category called "breakfast" with the information "Never" < "Rarely" < "Most days" < "Every day", we can assign to these strings the integers "0" < "1" < "2" < "3" respectively.

In [11]:
from sklearn.preprocessing import OrdinalEncoder

# Make copy to avoid changing original data 
label_X_train = X_train.copy()
label_X_valid = X_valid.copy()

# Apply ordinal encoder to each column with categorical data
ordinal_encoder = OrdinalEncoder()
label_X_train[object_cols] = ordinal_encoder.fit_transform(X_train[object_cols])
label_X_valid[object_cols] = ordinal_encoder.transform(X_valid[object_cols])

print("MAE from Approach 2 (Ordinal Encoding):") 
print(score_dataset(label_X_train, label_X_valid, y_train, y_valid))

MAE from Approach 2 (Ordinal Encoding):
175062.2967599411

3) One-Hot Encoding: One-hot encoding creates new columns indicating the presence (or absence) of each possible value in the original data. In contrast to ordinal encoding, one-hot encoding does not assume an ordering of the categories. Thus, you can expect this approach to work particularly well if there is no clear ordering in the categorical data (e.g., "Red" is neither more nor less than "Yellow"). We refer to categorical variables without an intrinsic ranking as nominal variables.

In [12]:
from sklearn.preprocessing import OneHotEncoder

# Apply one-hot encoder to each column with categorical data
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X_train[object_cols]))
OH_cols_valid = pd.DataFrame(OH_encoder.transform(X_valid[object_cols]))

# One-hot encoding removed index; put it back
OH_cols_train.index = X_train.index
OH_cols_valid.index = X_valid.index

# Remove categorical columns (will replace with one-hot encoding)
num_X_train = X_train.drop(object_cols, axis=1)
num_X_valid = X_valid.drop(object_cols, axis=1)

# Add one-hot encoded columns to numerical features
OH_X_train = pd.concat([num_X_train, OH_cols_train], axis=1)
OH_X_valid = pd.concat([num_X_valid, OH_cols_valid], axis=1)

# Ensure all columns have string type
OH_X_train.columns = OH_X_train.columns.astype(str)
OH_X_valid.columns = OH_X_valid.columns.astype(str)

print("MAE from Approach 3 (One-Hot Encoding):") 
print(score_dataset(OH_X_train, OH_X_valid, y_train, y_valid))

MAE from Approach 3 (One-Hot Encoding):
176703.63810751104

## Pipelines

Pipelines are a simple way to keep your data preprocessing and modeling code organized. Specifically, a pipeline bundles preprocessing and modeling steps so you can use the whole bundle as if it were a single step.

Many data scientists hack together models without pipelines, but pipelines have some important benefits. Those include:

1) Cleaner Code: Accounting for data at each step of preprocessing can get messy. With a pipeline, you won't need to manually keep track of your training and validation data at each step.
2) Fewer Bugs: There are fewer opportunities to misapply a step or forget a preprocessing step.
3) Easier to Productionize: It can be surprisingly hard to transition a model from a prototype to something deployable at scale. We won't go into the many related concerns here, but pipelines can help.
4) More Options for Model Validation: You will see an example in the next tutorial, which covers cross-validation.

In [13]:
# Separate target from predictors
y = data.Price
X = data.drop(['Price'], axis=1)

# Divide data into training and validation subsets
X_train_full, X_valid_full, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                                random_state=0)

# "Cardinality" means the number of unique values in a column
# Select categorical columns with relatively low cardinality (convenient but arbitrary)
categorical_cols = [cname for cname in X_train_full.columns if X_train_full[cname].nunique() < 10 and 
                        X_train_full[cname].dtype == "object"]

# Select numerical columns
numerical_cols = [cname for cname in X_train_full.columns if X_train_full[cname].dtype in ['int64', 'float64']]

# Keep selected columns only
my_cols = categorical_cols + numerical_cols
X_train = X_train_full[my_cols].copy()
X_valid = X_valid_full[my_cols].copy()

In [14]:
X_train.head()

,Type,Method,Regionname,Rooms,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
12167,u,S,Southern Metropolitan,1,5.0,3182.0,1.0,1.0,1.0,0.0,NaN,1940.0,-37.85984,144.9867,13240.0
6524,h,SA,Western Metropolitan,2,8.0,3016.0,2.0,2.0,1.0,193.0,NaN,NaN,-37.85800,144.9005,6380.0
8413,h,S,Western Metropolitan,3,12.6,3020.0,3.0,1.0,1.0,555.0,NaN,NaN,-37.79880,144.8220,3755.0
2919,u,SP,Northern Metropolitan,3,13.0,3046.0,3.0,1.0,1.0,265.0,NaN,1995.0,-37.70830,144.9158,8870.0
6043,h,S,Western Metropolitan,3,13.3,3020.0,3.0,1.0,2.0,673.0,673.0,1970.0,-37.76230,144.8272,4217.0

We construct the full pipeline in three steps.

1) Define Preprocessing Steps. The code below:

- imputes missing values in numerical data, and
- imputes missing values and applies a one-hot encoding to categorical data.

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

# Preprocessing for numerical data
numerical_transformer = SimpleImputer(strategy='constant')

# Preprocessing for categorical data
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])

2) Define the Model: Next, we define a random forest model with the familiar RandomForestRegressor class.

In [16]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=0)

3) Create and Evaluate the Pipeline. Finally, we use the Pipeline class to define a pipeline that bundles the preprocessing and modeling steps. There are a few important things to notice:

- With the pipeline, we preprocess the training data and fit the model in a single line of code. (In contrast, without a pipeline, we have to do imputation, one-hot encoding, and model training in separate steps. This becomes especially messy if we have to deal with both numerical and categorical variables!)
- With the pipeline, we supply the unprocessed features in X_valid to the predict() command, and the pipeline automatically preprocesses the features before generating predictions. (However, without a pipeline, we have to remember to preprocess the validation data before making predictions.)

In [17]:
from sklearn.metrics import mean_absolute_error

# Bundle preprocessing and modeling code in a pipeline
my_pipeline = Pipeline(steps=[('preprocessor', preprocessor),('model', model)])

# Preprocessing of training data, fit model 
my_pipeline.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
preds = my_pipeline.predict(X_valid)

# Evaluate the model
score = mean_absolute_error(y_valid, preds)
print('MAE:', score)

MAE: 160679.18917034855

## Cross validation

Cross-validation gives a more accurate measure of model quality, which is especially important if you are making a lot of modeling decisions. However, it can take longer to run, because it estimates multiple models (one for each fold).

In [18]:
# Select subset of predictors
cols_to_use = ['Rooms', 'Distance', 'Landsize', 'BuildingArea', 'YearBuilt']
X = data[cols_to_use]

# Select target
y = data.Price

Then, we define a pipeline that uses an imputer to fill in missing values and a random forest model to make predictions.

While it's possible to do cross-validation without pipelines, it is quite difficult! Using a pipeline will make the code remarkably straightforward.

In [19]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

my_pipeline = Pipeline(steps=[('preprocessor', SimpleImputer()),('model', RandomForestRegressor(n_estimators=50,random_state=0))])

In [20]:
from sklearn.model_selection import cross_val_score

# Multiply by -1 since sklearn calculates *negative* MAE
scores = -1 * cross_val_score(my_pipeline, X, y,cv=5,scoring='neg_mean_absolute_error')

print("MAE scores:\n", scores)

MAE scores:
 [301628.7893587  303164.4782723  287298.331666   236061.84754543
 260383.45111427]

In [21]:
print("Average MAE score (across experiments):")
print(scores.mean())

Average MAE score (across experiments):
277707.3795913405

Using cross-validation yields a much better measure of model quality, with the added benefit of cleaning up our code: note that we no longer need to keep track of separate training and validation sets. So, especially for small datasets, it's a good improvement!

## XGBoost

In this tutorial, you will learn how to build and optimize models with gradient boosting. This method dominates many Kaggle competitions and achieves state-of-the-art results on a variety of datasets.

For much of this course, you have made predictions with the random forest method, which achieves better performance than a single decision tree simply by averaging the predictions of many decision trees.

We refer to the random forest method as an "ensemble method". By definition, ensemble methods combine the predictions of several models (e.g., several trees, in the case of random forests).

Next, we'll learn about another ensemble method called gradient boosting.

Gradient boosting is a method that goes through cycles to iteratively add models into an ensemble.

It begins by initializing the ensemble with a single model, whose predictions can be pretty naive. (Even if its predictions are wildly inaccurate, subsequent additions to the ensemble will address those errors.)

Then, we start the cycle:

- First, we use the current ensemble to generate predictions for each observation in the dataset. To make a prediction, we add the predictions from all models in the ensemble.
- These predictions are used to calculate a loss function (like mean squared error, for instance).
- Then, we use the loss function to fit a new model that will be added to the ensemble. Specifically, we determine model parameters so that adding this new model to the ensemble will reduce the loss. (Side note: The "gradient" in "gradient boosting" refers to the fact that we'll use gradient descent on the loss function to determine the parameters in this new model.)
- Finally, we add the new model to ensemble, and ...
- ... repeat!

In [22]:
# Select subset of predictors
cols_to_use = ['Rooms', 'Distance', 'Landsize', 'BuildingArea', 'YearBuilt']
X = data[cols_to_use]

# Select target
y = data.Price

# Separate data into training and validation sets
X_train, X_valid, y_train, y_valid = train_test_split(X, y)

In [23]:
from xgboost import XGBRegressor

my_model = XGBRegressor()
my_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [24]:
from sklearn.metrics import mean_absolute_error

predictions = my_model.predict(X_valid)
print("Mean Absolute Error: " + str(mean_absolute_error(predictions, y_valid)))

Mean Absolute Error: 243455.4612447073

n_estimators specifies how many times to go through the modeling cycle described above. It is equal to the number of models that we include in the ensemble.

Too low a value causes underfitting, which leads to inaccurate predictions on both training data and test data.
Too high a value causes overfitting, which causes accurate predictions on training data, but inaccurate predictions on test data (which is what we care about).
Typical values range from 100-1000, though this depends a lot on the learning_rate parameter discussed below.

In [25]:
my_model = XGBRegressor(n_estimators=500)
my_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

early_stopping_rounds offers a way to automatically find the ideal value for n_estimators. Early stopping causes the model to stop iterating when the validation score stops improving, even if we aren't at the hard stop for n_estimators. It's smart to set a high value for n_estimators and then use early_stopping_rounds to find the optimal time to stop iterating.

In [26]:
my_model = XGBRegressor(n_estimators=500,early_stopping_rounds=5,verbose_eval=False)
my_model.fit(X_train, y_train, eval_set=[(X_valid, y_valid)])

[0]	validation_0-rmse:574873.58870
[1]	validation_0-rmse:517889.56433
[2]	validation_0-rmse:482256.10379
[3]	validation_0-rmse:459074.77481
[4]	validation_0-rmse:443033.66232
[5]	validation_0-rmse:432807.14017
[6]	validation_0-rmse:425395.83604
[7]	validation_0-rmse:419885.62314
[8]	validation_0-rmse:416302.34072
[9]	validation_0-rmse:415145.29209
[10]	validation_0-rmse:410729.62559
[11]	validation_0-rmse:409126.98733
[12]	validation_0-rmse:407623.74621
[13]	validation_0-rmse:405629.05479
[14]	validation_0-rmse:405405.28191
[15]	validation_0-rmse:405312.81379
[16]	validation_0-rmse:404227.11270
[17]	validation_0-rmse:400466.13536
[18]	validation_0-rmse:400377.56543
[19]	validation_0-rmse:399428.45349
[20]	validation_0-rmse:398702.74513
[21]	validation_0-rmse:396959.27110
[22]	validation_0-rmse:396536.64508
[23]	validation_0-rmse:396478.99944
[24]	validation_0-rmse:396163.59281
[25]	validation_0-rmse:395964.69144
[26]	validation_0-rmse:394387.83149
[27]	validation_0-rmse:394061.18188
[28]	validation_0-rmse:393836.47341
[29]	validation_0-rmse:393778.01612

/opt/anaconda3/lib/python3.13/site-packages/xgboost/callback.py:386: UserWarning: [13:05:03] WARNING: /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_7eg2b3w9sf/croot/xgboost-split_1749630922962/work/src/learner.cc:738:
Parameters: { "verbose_eval" } are not used.

  self.starting_round = model.num_boosted_rounds()

[30]	validation_0-rmse:393808.06027
[31]	validation_0-rmse:393397.14546
[32]	validation_0-rmse:393338.59252
[33]	validation_0-rmse:393072.78042
[34]	validation_0-rmse:392886.01252
[35]	validation_0-rmse:391923.71745
[36]	validation_0-rmse:391711.20841
[37]	validation_0-rmse:390924.37694
[38]	validation_0-rmse:391409.48451
[39]	validation_0-rmse:391666.53766
[40]	validation_0-rmse:391490.00404
[41]	validation_0-rmse:390738.41166
[42]	validation_0-rmse:390672.86732
[43]	validation_0-rmse:391051.24895
[44]	validation_0-rmse:390866.32496
[45]	validation_0-rmse:389924.96310
[46]	validation_0-rmse:389765.76647
[47]	validation_0-rmse:390247.42334
[48]	validation_0-rmse:390570.75278
[49]	validation_0-rmse:390384.54584
[50]	validation_0-rmse:390307.96756
[51]	validation_0-rmse:390296.62616

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=5,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In general, a small learning rate and large number of estimators will yield more accurate XGBoost models, though it will also take the model longer to train since it does more iterations through the cycle. As default, XGBoost sets learning_rate=0.1

In [27]:
my_model = XGBRegressor(n_estimators=1000, learning_rate=0.05,verbose=False,early_stopping_rounds=5)
my_model.fit(X_train, y_train, eval_set=[(X_valid, y_valid)])

[0]	validation_0-rmse:650462.22857
[1]	validation_0-rmse:634940.25784
[2]	validation_0-rmse:620591.57313
[3]	validation_0-rmse:607276.23893
[4]	validation_0-rmse:594749.73752
[5]	validation_0-rmse:583023.28791
[6]	validation_0-rmse:572011.62451
[7]	validation_0-rmse:561969.07382
[8]	validation_0-rmse:552722.37027
[9]	validation_0-rmse:543997.68575
[10]	validation_0-rmse:536208.87048
[11]	validation_0-rmse:528539.14202
[12]	validation_0-rmse:521428.97140
[13]	validation_0-rmse:514598.53187
[14]	validation_0-rmse:507973.36050
[15]	validation_0-rmse:502110.11137
[16]	validation_0-rmse:496851.35880
[17]	validation_0-rmse:491562.04304
[18]	validation_0-rmse:486851.24256
[19]	validation_0-rmse:482311.64126
[20]	validation_0-rmse:477863.36434
[21]	validation_0-rmse:473949.44708
[22]	validation_0-rmse:470000.30598
[23]	validation_0-rmse:466908.28210

/opt/anaconda3/lib/python3.13/site-packages/xgboost/callback.py:386: UserWarning: [13:05:03] WARNING: /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_7eg2b3w9sf/croot/xgboost-split_1749630922962/work/src/learner.cc:738:
Parameters: { "verbose" } are not used.

  self.starting_round = model.num_boosted_rounds()

[24]	validation_0-rmse:463408.15370
[25]	validation_0-rmse:460068.08407
[26]	validation_0-rmse:457541.51300
[27]	validation_0-rmse:454845.65928
[28]	validation_0-rmse:452512.52528
[29]	validation_0-rmse:449867.02266
[30]	validation_0-rmse:447292.23872
[31]	validation_0-rmse:445189.74692
[32]	validation_0-rmse:443107.51204
[33]	validation_0-rmse:441111.76875
[34]	validation_0-rmse:439549.48338
[35]	validation_0-rmse:438154.78041
[36]	validation_0-rmse:436710.90845
[37]	validation_0-rmse:435255.61656
[38]	validation_0-rmse:434083.15012
[39]	validation_0-rmse:432931.75759
[40]	validation_0-rmse:431810.69674
[41]	validation_0-rmse:430599.18039
[42]	validation_0-rmse:429431.27681
[43]	validation_0-rmse:428043.87747
[44]	validation_0-rmse:426977.41537
[45]	validation_0-rmse:426156.77819
[46]	validation_0-rmse:424702.60387
[47]	validation_0-rmse:423741.63518
[48]	validation_0-rmse:422790.89245
[49]	validation_0-rmse:421808.09556
[50]	validation_0-rmse:420846.39087
[51]	validation_0-rmse:420276.93112
[52]	validation_0-rmse:419120.06711
[53]	validation_0-rmse:418531.75892
[54]	validation_0-rmse:418103.20913
[55]	validation_0-rmse:417297.10806
[56]	validation_0-rmse:416831.07665
[57]	validation_0-rmse:416304.34354
[58]	validation_0-rmse:415622.19899
[59]	validation_0-rmse:414557.20618
[60]	validation_0-rmse:413846.12480
[61]	validation_0-rmse:413061.78348
[62]	validation_0-rmse:412719.53539
[63]	validation_0-rmse:411951.48451
[64]	validation_0-rmse:411496.21487
[65]	validation_0-rmse:411161.48683
[66]	validation_0-rmse:410661.82756
[67]	validation_0-rmse:410010.37744
[68]	validation_0-rmse:409236.55804
[69]	validation_0-rmse:408998.90410
[70]	validation_0-rmse:408688.31791
[71]	validation_0-rmse:408129.08492
[72]	validation_0-rmse:407663.17364
[73]	validation_0-rmse:407166.34196
[74]	validation_0-rmse:406618.05503
[75]	validation_0-rmse:406461.43923
[76]	validation_0-rmse:406260.17242
[77]	validation_0-rmse:405971.91645
[78]	validation_0-rmse:405522.65215
[79]	validation_0-rmse:405181.18515
[80]	validation_0-rmse:404907.28573
[81]	validation_0-rmse:404802.64273
[82]	validation_0-rmse:404611.12499
[83]	validation_0-rmse:404300.91919
[84]	validation_0-rmse:404063.74101
[85]	validation_0-rmse:403322.26031
[86]	validation_0-rmse:402909.58481
[87]	validation_0-rmse:402689.90114
[88]	validation_0-rmse:402476.27498
[89]	validation_0-rmse:402333.43587
[90]	validation_0-rmse:402244.23677
[91]	validation_0-rmse:401944.49362
[92]	validation_0-rmse:401845.03002
[93]	validation_0-rmse:401628.69486
[94]	validation_0-rmse:401597.25671
[95]	validation_0-rmse:401438.30822
[96]	validation_0-rmse:401272.85399
[97]	validation_0-rmse:401198.43066
[98]	validation_0-rmse:401004.17427
[99]	validation_0-rmse:400746.94827
[100]	validation_0-rmse:400715.08121
[101]	validation_0-rmse:400627.59646
[102]	validation_0-rmse:400228.65764
[103]	validation_0-rmse:400052.59389
[104]	validation_0-rmse:400026.98696
[105]	validation_0-rmse:399963.65342
[106]	validation_0-rmse:399965.21905
[107]	validation_0-rmse:399684.59635
[108]	validation_0-rmse:399114.88353
[109]	validation_0-rmse:399089.82079
[110]	validation_0-rmse:399012.70830
[111]	validation_0-rmse:398859.73906
[112]	validation_0-rmse:398868.30554
[113]	validation_0-rmse:398606.76155
[114]	validation_0-rmse:398584.88733
[115]	validation_0-rmse:398495.60696
[116]	validation_0-rmse:398159.97679
[117]	validation_0-rmse:397934.70265
[118]	validation_0-rmse:397884.60481
[119]	validation_0-rmse:397743.76931
[120]	validation_0-rmse:397635.50987
[121]	validation_0-rmse:397502.01856
[122]	validation_0-rmse:397474.66524
[123]	validation_0-rmse:397437.09619
[124]	validation_0-rmse:397361.52199
[125]	validation_0-rmse:397200.39827
[126]	validation_0-rmse:397179.53487
[127]	validation_0-rmse:396983.14064
[128]	validation_0-rmse:396717.14301
[129]	validation_0-rmse:396671.85381
[130]	validation_0-rmse:396679.16338
[131]	validation_0-rmse:396588.88779
[132]	validation_0-rmse:396335.94114
[133]	validation_0-rmse:396270.42336
[134]	validation_0-rmse:396210.76379
[135]	validation_0-rmse:395589.25711
[136]	validation_0-rmse:395513.54126
[137]	validation_0-rmse:395433.73840
[138]	validation_0-rmse:395397.33793
[139]	validation_0-rmse:395190.33769
[140]	validation_0-rmse:395146.87546
[141]	validation_0-rmse:395106.74053
[142]	validation_0-rmse:394730.14487
[143]	validation_0-rmse:394543.83007
[144]	validation_0-rmse:394518.11710
[145]	validation_0-rmse:394580.74259
[146]	validation_0-rmse:394367.82239
[147]	validation_0-rmse:394272.70585
[148]	validation_0-rmse:394148.04711
[149]	validation_0-rmse:394064.29523
[150]	validation_0-rmse:394101.77923
[151]	validation_0-rmse:394053.07487
[152]	validation_0-rmse:393974.10322
[153]	validation_0-rmse:393859.66204
[154]	validation_0-rmse:393783.37179
[155]	validation_0-rmse:393756.61401
[156]	validation_0-rmse:393477.42858
[157]	validation_0-rmse:393379.14306
[158]	validation_0-rmse:393078.42974
[159]	validation_0-rmse:393036.91645
[160]	validation_0-rmse:393071.10393
[161]	validation_0-rmse:392914.14774
[162]	validation_0-rmse:392665.69735
[163]	validation_0-rmse:392716.03108
[164]	validation_0-rmse:392668.69757
[165]	validation_0-rmse:392681.09113
[166]	validation_0-rmse:392659.40109
[167]	validation_0-rmse:392616.98414
[168]	validation_0-rmse:392680.52527
[169]	validation_0-rmse:392609.21858
[170]	validation_0-rmse:392499.17110
[171]	validation_0-rmse:392464.69363
[172]	validation_0-rmse:392290.53016
[173]	validation_0-rmse:392323.24195
[174]	validation_0-rmse:392242.44002
[175]	validation_0-rmse:392249.04488
[176]	validation_0-rmse:392126.79627
[177]	validation_0-rmse:391861.67725
[178]	validation_0-rmse:391830.85978
[179]	validation_0-rmse:391759.46222
[180]	validation_0-rmse:391752.71021
[181]	validation_0-rmse:391692.26384
[182]	validation_0-rmse:391640.15667
[183]	validation_0-rmse:391619.35771
[184]	validation_0-rmse:391638.69255
[185]	validation_0-rmse:391322.90822
[186]	validation_0-rmse:391315.17271
[187]	validation_0-rmse:391185.46807
[188]	validation_0-rmse:391159.91776
[189]	validation_0-rmse:391170.17054
[190]	validation_0-rmse:391142.36431
[191]	validation_0-rmse:391033.46591
[192]	validation_0-rmse:390723.82121
[193]	validation_0-rmse:390586.41167
[194]	validation_0-rmse:390441.30051
[195]	validation_0-rmse:390436.04678
[196]	validation_0-rmse:390062.95611
[197]	validation_0-rmse:389649.27842
[198]	validation_0-rmse:389643.78248
[199]	validation_0-rmse:389630.48932
[200]	validation_0-rmse:389526.69866
[201]	validation_0-rmse:389436.61463
[202]	validation_0-rmse:389236.86843
[203]	validation_0-rmse:389221.05505
[204]	validation_0-rmse:389037.26374
[205]	validation_0-rmse:388943.63458
[206]	validation_0-rmse:388841.77007
[207]	validation_0-rmse:388729.59755
[208]	validation_0-rmse:388747.38424
[209]	validation_0-rmse:388666.10158
[210]	validation_0-rmse:388567.18672
[211]	validation_0-rmse:388474.01297
[212]	validation_0-rmse:388372.81072
[213]	validation_0-rmse:388241.78064
[214]	validation_0-rmse:388182.31215
[215]	validation_0-rmse:388194.74678
[216]	validation_0-rmse:388091.04547
[217]	validation_0-rmse:388018.51360
[218]	validation_0-rmse:387992.66072
[219]	validation_0-rmse:387990.96176
[220]	validation_0-rmse:387993.01159
[221]	validation_0-rmse:387812.25157
[222]	validation_0-rmse:387716.57097
[223]	validation_0-rmse:387709.50619
[224]	validation_0-rmse:387706.16318
[225]	validation_0-rmse:387644.41922
[226]	validation_0-rmse:387568.95123
[227]	validation_0-rmse:387590.97259
[228]	validation_0-rmse:387510.35758
[229]	validation_0-rmse:387281.57298
[230]	validation_0-rmse:387290.82725
[231]	validation_0-rmse:387288.22714
[232]	validation_0-rmse:387291.38081
[233]	validation_0-rmse:387178.94011
[234]	validation_0-rmse:387072.56515
[235]	validation_0-rmse:387041.02613
[236]	validation_0-rmse:387029.79412
[237]	validation_0-rmse:387070.03266
[238]	validation_0-rmse:387044.79115
[239]	validation_0-rmse:387033.76412
[240]	validation_0-rmse:386949.95414
[241]	validation_0-rmse:386907.33535
[242]	validation_0-rmse:386872.77727
[243]	validation_0-rmse:386759.90931
[244]	validation_0-rmse:386524.66640
[245]	validation_0-rmse:386473.22189
[246]	validation_0-rmse:386393.89680
[247]	validation_0-rmse:386395.50586
[248]	validation_0-rmse:386319.90953
[249]	validation_0-rmse:386337.49969
[250]	validation_0-rmse:386341.92290
[251]	validation_0-rmse:386300.84695
[252]	validation_0-rmse:386377.90405
[253]	validation_0-rmse:386366.97362
[254]	validation_0-rmse:386335.44739
[255]	validation_0-rmse:386326.80485
[256]	validation_0-rmse:386129.96897
[257]	validation_0-rmse:386059.74138
[258]	validation_0-rmse:386068.22119
[259]	validation_0-rmse:386058.15505
[260]	validation_0-rmse:386063.40119
[261]	validation_0-rmse:386033.08342
[262]	validation_0-rmse:386062.82665
[263]	validation_0-rmse:386031.30409
[264]	validation_0-rmse:385979.16549
[265]	validation_0-rmse:385897.23397
[266]	validation_0-rmse:385776.79732
[267]	validation_0-rmse:385736.38455
[268]	validation_0-rmse:385668.87960
[269]	validation_0-rmse:385781.99887
[270]	validation_0-rmse:385808.84665
[271]	validation_0-rmse:385811.53351
[272]	validation_0-rmse:385786.12976

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=5,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=1000,
             n_jobs=None, num_parallel_tree=None, ...)

On larger datasets where runtime is a consideration, you can use parallelism to build your models faster. It's common to set the parameter n_jobs equal to the number of cores on your machine. On smaller datasets, this won't help.

In [28]:
my_model = XGBRegressor(n_estimators=1000, learning_rate=0.05, n_jobs=4,early_stopping_rounds=5, verbose=False)
my_model.fit(X_train, y_train, eval_set=[(X_valid, y_valid)])

[0]	validation_0-rmse:650462.22857
[1]	validation_0-rmse:634940.25784
[2]	validation_0-rmse:620591.57313
[3]	validation_0-rmse:607276.23893
[4]	validation_0-rmse:594749.73752
[5]	validation_0-rmse:583023.28791
[6]	validation_0-rmse:572011.62451
[7]	validation_0-rmse:561969.07382
[8]	validation_0-rmse:552722.37027
[9]	validation_0-rmse:543997.68575
[10]	validation_0-rmse:536208.87048

/opt/anaconda3/lib/python3.13/site-packages/xgboost/callback.py:386: UserWarning: [13:05:09] WARNING: /var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_7eg2b3w9sf/croot/xgboost-split_1749630922962/work/src/learner.cc:738:
Parameters: { "verbose" } are not used.

  self.starting_round = model.num_boosted_rounds()

[11]	validation_0-rmse:528539.14202
[12]	validation_0-rmse:521428.97140
[13]	validation_0-rmse:514598.53187
[14]	validation_0-rmse:507973.36050
[15]	validation_0-rmse:502110.11137
[16]	validation_0-rmse:496851.35880
[17]	validation_0-rmse:491562.04304
[18]	validation_0-rmse:486851.24256
[19]	validation_0-rmse:482311.64126
[20]	validation_0-rmse:477863.36434
[21]	validation_0-rmse:473949.44708
[22]	validation_0-rmse:470000.30598
[23]	validation_0-rmse:466908.28210
[24]	validation_0-rmse:463408.15370
[25]	validation_0-rmse:460068.08407
[26]	validation_0-rmse:457541.51300
[27]	validation_0-rmse:454845.65928
[28]	validation_0-rmse:452512.52528
[29]	validation_0-rmse:449867.02266
[30]	validation_0-rmse:447292.23872
[31]	validation_0-rmse:445189.74692
[32]	validation_0-rmse:443107.51204
[33]	validation_0-rmse:441111.76875
[34]	validation_0-rmse:439549.48338
[35]	validation_0-rmse:438154.78041
[36]	validation_0-rmse:436710.90845
[37]	validation_0-rmse:435255.61656
[38]	validation_0-rmse:434083.15012
[39]	validation_0-rmse:432931.75759
[40]	validation_0-rmse:431810.69674
[41]	validation_0-rmse:430599.18039
[42]	validation_0-rmse:429431.27681
[43]	validation_0-rmse:428043.87747
[44]	validation_0-rmse:426977.41537
[45]	validation_0-rmse:426156.77819
[46]	validation_0-rmse:424702.60387
[47]	validation_0-rmse:423741.63518
[48]	validation_0-rmse:422790.89245
[49]	validation_0-rmse:421808.09556
[50]	validation_0-rmse:420846.39087
[51]	validation_0-rmse:420276.93112
[52]	validation_0-rmse:419120.06711
[53]	validation_0-rmse:418531.75892
[54]	validation_0-rmse:418103.20913
[55]	validation_0-rmse:417297.10806
[56]	validation_0-rmse:416831.07665
[57]	validation_0-rmse:416304.34354
[58]	validation_0-rmse:415622.19899
[59]	validation_0-rmse:414557.20618
[60]	validation_0-rmse:413846.12480
[61]	validation_0-rmse:413061.78348
[62]	validation_0-rmse:412719.53539
[63]	validation_0-rmse:411951.48451
[64]	validation_0-rmse:411496.21487
[65]	validation_0-rmse:411161.48683
[66]	validation_0-rmse:410661.82756
[67]	validation_0-rmse:410010.37744
[68]	validation_0-rmse:409236.55804
[69]	validation_0-rmse:408998.90410
[70]	validation_0-rmse:408688.31791
[71]	validation_0-rmse:408129.08492
[72]	validation_0-rmse:407663.17364
[73]	validation_0-rmse:407166.34196
[74]	validation_0-rmse:406618.05503
[75]	validation_0-rmse:406461.43923
[76]	validation_0-rmse:406260.17242
[77]	validation_0-rmse:405971.91645
[78]	validation_0-rmse:405522.65215
[79]	validation_0-rmse:405181.18515
[80]	validation_0-rmse:404907.28573
[81]	validation_0-rmse:404802.64273
[82]	validation_0-rmse:404611.12499
[83]	validation_0-rmse:404300.91919
[84]	validation_0-rmse:404063.74101
[85]	validation_0-rmse:403322.26031
[86]	validation_0-rmse:402909.58481
[87]	validation_0-rmse:402689.90114
[88]	validation_0-rmse:402476.27498
[89]	validation_0-rmse:402333.43587
[90]	validation_0-rmse:402244.23677
[91]	validation_0-rmse:401944.49362
[92]	validation_0-rmse:401845.03002
[93]	validation_0-rmse:401628.69486
[94]	validation_0-rmse:401597.25671
[95]	validation_0-rmse:401438.30822
[96]	validation_0-rmse:401272.85399
[97]	validation_0-rmse:401198.43066
[98]	validation_0-rmse:401004.17427
[99]	validation_0-rmse:400746.94827
[100]	validation_0-rmse:400715.08121
[101]	validation_0-rmse:400627.59646
[102]	validation_0-rmse:400228.65764
[103]	validation_0-rmse:400052.59389
[104]	validation_0-rmse:400026.98696
[105]	validation_0-rmse:399963.65342
[106]	validation_0-rmse:399965.21905
[107]	validation_0-rmse:399684.59635
[108]	validation_0-rmse:399114.88353
[109]	validation_0-rmse:399089.82079
[110]	validation_0-rmse:399012.70830
[111]	validation_0-rmse:398859.73906
[112]	validation_0-rmse:398868.30554
[113]	validation_0-rmse:398606.76155
[114]	validation_0-rmse:398584.88733
[115]	validation_0-rmse:398495.60696
[116]	validation_0-rmse:398159.97679
[117]	validation_0-rmse:397934.70265
[118]	validation_0-rmse:397884.60481
[119]	validation_0-rmse:397743.76931
[120]	validation_0-rmse:397635.50987
[121]	validation_0-rmse:397502.01856
[122]	validation_0-rmse:397474.66524
[123]	validation_0-rmse:397437.09619
[124]	validation_0-rmse:397361.52199
[125]	validation_0-rmse:397200.39827
[126]	validation_0-rmse:397179.53487
[127]	validation_0-rmse:396983.14064
[128]	validation_0-rmse:396717.14301
[129]	validation_0-rmse:396671.85381
[130]	validation_0-rmse:396679.16338
[131]	validation_0-rmse:396588.88779
[132]	validation_0-rmse:396335.94114
[133]	validation_0-rmse:396270.42336
[134]	validation_0-rmse:396210.76379
[135]	validation_0-rmse:395589.25711
[136]	validation_0-rmse:395513.54126
[137]	validation_0-rmse:395433.73840
[138]	validation_0-rmse:395397.33793
[139]	validation_0-rmse:395190.33769
[140]	validation_0-rmse:395146.87546
[141]	validation_0-rmse:395106.74053
[142]	validation_0-rmse:394730.14487
[143]	validation_0-rmse:394543.83007
[144]	validation_0-rmse:394518.11710
[145]	validation_0-rmse:394580.74259
[146]	validation_0-rmse:394367.82239
[147]	validation_0-rmse:394272.70585
[148]	validation_0-rmse:394148.04711
[149]	validation_0-rmse:394064.29523
[150]	validation_0-rmse:394101.77923
[151]	validation_0-rmse:394053.07487
[152]	validation_0-rmse:393974.10322
[153]	validation_0-rmse:393859.66204
[154]	validation_0-rmse:393783.37179
[155]	validation_0-rmse:393756.61401
[156]	validation_0-rmse:393477.42858
[157]	validation_0-rmse:393379.14306
[158]	validation_0-rmse:393078.42974
[159]	validation_0-rmse:393036.91645
[160]	validation_0-rmse:393071.10393
[161]	validation_0-rmse:392914.14774
[162]	validation_0-rmse:392665.69735
[163]	validation_0-rmse:392716.03108
[164]	validation_0-rmse:392668.69757
[165]	validation_0-rmse:392681.09113
[166]	validation_0-rmse:392659.40109
[167]	validation_0-rmse:392616.98414
[168]	validation_0-rmse:392680.52527
[169]	validation_0-rmse:392609.21858
[170]	validation_0-rmse:392499.17110
[171]	validation_0-rmse:392464.69363
[172]	validation_0-rmse:392290.53016
[173]	validation_0-rmse:392323.24195
[174]	validation_0-rmse:392242.44002
[175]	validation_0-rmse:392249.04488
[176]	validation_0-rmse:392126.79627
[177]	validation_0-rmse:391861.67725
[178]	validation_0-rmse:391830.85978
[179]	validation_0-rmse:391759.46222
[180]	validation_0-rmse:391752.71021
[181]	validation_0-rmse:391692.26384
[182]	validation_0-rmse:391640.15667
[183]	validation_0-rmse:391619.35771
[184]	validation_0-rmse:391638.69255
[185]	validation_0-rmse:391322.90822
[186]	validation_0-rmse:391315.17271
[187]	validation_0-rmse:391185.46807
[188]	validation_0-rmse:391159.91776
[189]	validation_0-rmse:391170.17054
[190]	validation_0-rmse:391142.36431
[191]	validation_0-rmse:391033.46591
[192]	validation_0-rmse:390723.82121
[193]	validation_0-rmse:390586.41167
[194]	validation_0-rmse:390441.30051
[195]	validation_0-rmse:390436.04678
[196]	validation_0-rmse:390062.95611
[197]	validation_0-rmse:389649.27842
[198]	validation_0-rmse:389643.78248
[199]	validation_0-rmse:389630.48932
[200]	validation_0-rmse:389526.69866
[201]	validation_0-rmse:389436.61463
[202]	validation_0-rmse:389236.86843
[203]	validation_0-rmse:389221.05505
[204]	validation_0-rmse:389037.26374
[205]	validation_0-rmse:388943.63458
[206]	validation_0-rmse:388841.77007
[207]	validation_0-rmse:388729.59755
[208]	validation_0-rmse:388747.38424
[209]	validation_0-rmse:388666.10158
[210]	validation_0-rmse:388567.18672
[211]	validation_0-rmse:388474.01297
[212]	validation_0-rmse:388372.81072
[213]	validation_0-rmse:388241.78064
[214]	validation_0-rmse:388182.31215
[215]	validation_0-rmse:388194.74678
[216]	validation_0-rmse:388091.04547
[217]	validation_0-rmse:388018.51360
[218]	validation_0-rmse:387992.66072
[219]	validation_0-rmse:387990.96176
[220]	validation_0-rmse:387993.01159
[221]	validation_0-rmse:387812.25157
[222]	validation_0-rmse:387716.57097
[223]	validation_0-rmse:387709.50619
[224]	validation_0-rmse:387706.16318
[225]	validation_0-rmse:387644.41922
[226]	validation_0-rmse:387568.95123
[227]	validation_0-rmse:387590.97259
[228]	validation_0-rmse:387510.35758
[229]	validation_0-rmse:387281.57298
[230]	validation_0-rmse:387290.82725
[231]	validation_0-rmse:387288.22714
[232]	validation_0-rmse:387291.38081
[233]	validation_0-rmse:387178.94011
[234]	validation_0-rmse:387072.56515
[235]	validation_0-rmse:387041.02613
[236]	validation_0-rmse:387029.79412
[237]	validation_0-rmse:387070.03266
[238]	validation_0-rmse:387044.79115
[239]	validation_0-rmse:387033.76412
[240]	validation_0-rmse:386949.95414
[241]	validation_0-rmse:386907.33535
[242]	validation_0-rmse:386872.77727
[243]	validation_0-rmse:386759.90931
[244]	validation_0-rmse:386524.66640
[245]	validation_0-rmse:386473.22189
[246]	validation_0-rmse:386393.89680
[247]	validation_0-rmse:386395.50586
[248]	validation_0-rmse:386319.90953
[249]	validation_0-rmse:386337.49969
[250]	validation_0-rmse:386341.92290
[251]	validation_0-rmse:386300.84695
[252]	validation_0-rmse:386377.90405
[253]	validation_0-rmse:386366.97362
[254]	validation_0-rmse:386335.44739
[255]	validation_0-rmse:386326.80485
[256]	validation_0-rmse:386129.96897
[257]	validation_0-rmse:386059.74138
[258]	validation_0-rmse:386068.22119
[259]	validation_0-rmse:386058.15505
[260]	validation_0-rmse:386063.40119
[261]	validation_0-rmse:386033.08342
[262]	validation_0-rmse:386062.82665
[263]	validation_0-rmse:386031.30409
[264]	validation_0-rmse:385979.16549
[265]	validation_0-rmse:385897.23397
[266]	validation_0-rmse:385776.79732
[267]	validation_0-rmse:385736.38455
[268]	validation_0-rmse:385668.87960
[269]	validation_0-rmse:385781.99887
[270]	validation_0-rmse:385808.84665
[271]	validation_0-rmse:385811.53351
[272]	validation_0-rmse:385786.12976
[273]	validation_0-rmse:385791.43611

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=5,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=1000,
             n_jobs=4, num_parallel_tree=None, ...)